version: '3.8'

services:
  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    image: backend:latest
    container_name: backend_task
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    container_name: frontend_task
    env_file:
      - ./frontend/.env.local

